#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD1Ja9kgnwTKWNHfZJc0YClBVJ5hISO5LJs1DXFXAaIqrVxN5eWwOITz5+GPHr3N60vjAp1DoLzHWK4C+Ajk2eoJF7VAD1HQHgIG1gs/k4t+IhHb2sqo0Lt2eSPN8noJciNgSiXSaVJ23swNRKO/pvjJUg7bjv+Pe6xbeaCmt2lI2OREF6wI16e/NGB17OirTie7UiJUCMEhaGIBkZI2c4xWUdpGHg3zV3xGrqoVXTyBPtQtBYG7KsTox9camt0bnEPfVfI+RbG3JAfKTxSVQraTWJGm1r4poD8jVpxmV5s82ld8VRLXhnaNZoH+33QeVdBm2BFn7TwtJ9x7KL7/ZQ9 aws-key     
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTsxHs1lOx5p4vnEePEgzaLfrtgjqRR8yArUnrjy9e7tOQcdlMeYT8lHrqxoDUrQb31cjP7m9dKzPQHZBQrNgDcqgC2HsdsayAb2bPmqIUnGVqdm9yMI3D03N4Q5i95g/6MRl7OYFpwIDqjB01D6pv6NBsg2yEc6t3CNw7sIzQMuliMBYwzfQbokssBPf7oEeqE+l/d/B4iugDV+f+826upAQrjatrmyykk5o3Slxzuu4W3WpryYmCL4NwdS3rY3/gYxE6RAU7FW41MEogKL32O+xE/8XJGN/wcXdL7u1IlGbAYuG+63ybpNW4qo6ZSWaxxeL1eUabroJgmy4yWjbJ aws-key       
ssh_pwauth: false
disable_root: false 
package_update: true
packages:
  - curl 
  - wget 
